"""init schema

Revision ID: 0fc31956c3c4
Revises: 707bfbed098f
Create Date: 2026-01-15 15:01:37.279456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fc31956c3c4'
down_revision: Union[str, Sequence[str], None] = '707bfbed098f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('host_user_id', sa.UUID(), nullable=False),
    sa.Column('join_code_hash', sa.String(length=255), nullable=False),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('turn_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('current_turn', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('faction_name', sa.String(length=80), nullable=False),
    sa.Column('is_host', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'faction_name', name='uq_players_game_faction'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_players_game_user')
    )
    op.create_index(op.f('ix_players_game_id'), 'players', ['game_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'number', name='uq_turns_game_number')
    )
    op.create_index(op.f('ix_turns_game_id'), 'turns', ['game_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'player_id', 'kind', 'target_id', name='uq_orders_turn_player_kind_target')
    )
    op.create_index(op.f('ix_orders_game_id'), 'orders', ['game_id'], unique=False)
    op.create_index(op.f('ix_orders_player_id'), 'orders', ['player_id'], unique=False)
    op.create_index(op.f('ix_orders_turn_id'), 'orders', ['turn_id'], unique=False)
    op.create_table('turn_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'player_id', name='uq_turn_submissions_turn_player')
    )
    op.create_index(op.f('ix_turn_submissions_game_id'), 'turn_submissions', ['game_id'], unique=False)
    op.create_index(op.f('ix_turn_submissions_player_id'), 'turn_submissions', ['player_id'], unique=False)
    op.create_index(op.f('ix_turn_submissions_turn_id'), 'turn_submissions', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_submissions_turn_id'), table_name='turn_submissions')
    op.drop_index(op.f('ix_turn_submissions_player_id'), table_name='turn_submissions')
    op.drop_index(op.f('ix_turn_submissions_game_id'), table_name='turn_submissions')
    op.drop_table('turn_submissions')
    op.drop_index(op.f('ix_orders_turn_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_player_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_game_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_turns_game_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_players_game_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
